export enum WALLET_TYPE {
    BUY_CREDIT = 0,
    BUY_SUBSCRIPTION = 1,
    REFUND = 2,
    ADMIN_ADJUSTMENT = 3,
    USE_SERVICES = 4,
    OCR_EMBEDDING = 5,
    QUIZ_GENERATION = 6,
    FLASHCARD_GENERATION = 7,
}
