# Minimal Dockerfile for Prisma Migrations
FROM node:20-alpine

RUN corepack enable && corepack prepare pnpm@10.11.0 --activate

WORKDIR /app

COPY package.json pnpm-lock.yaml ./
COPY libs ./libs

# Install only what's needed for prisma
RUN pnpm install --frozen-lockfile && \
    pnpm prisma:merge

CMD ["npx", "prisma", "migrate", "deploy", "--schema=libs/database/src/schema.prisma"]
