# Minimal Dockerfile for Prisma Migrations
FROM node:20-alpine

RUN corepack enable && corepack prepare yarn@4.9.2 --activate

WORKDIR /app

COPY package.json yarn.lock .yarnrc.yml ./
COPY libs ./libs

RUN yarn install --immutable && \
    yarn prisma:merge

CMD ["npx", "prisma", "migrate", "deploy", "--schema=libs/database/src/schema.prisma"]
