# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from . import r2_pb2 as r2__pb2


class R2ServiceStub(object):
    """R2 Storage Service - Quản lý file trên Cloudflare R2
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.UploadFile = channel.unary_unary(
                '/r2.R2Service/UploadFile',
                request_serializer=r2__pb2.UploadFileRequest.SerializeToString,
                response_deserializer=r2__pb2.UploadFileResponse.FromString,
                )
        self.GetFileUrl = channel.unary_unary(
                '/r2.R2Service/GetFileUrl',
                request_serializer=r2__pb2.GetFileUrlRequest.SerializeToString,
                response_deserializer=r2__pb2.GetFileUrlResponse.FromString,
                )
        self.DeleteFile = channel.unary_unary(
                '/r2.R2Service/DeleteFile',
                request_serializer=r2__pb2.DeleteFileRequest.SerializeToString,
                response_deserializer=r2__pb2.DeleteFileResponse.FromString,
                )
        self.ListUserFiles = channel.unary_unary(
                '/r2.R2Service/ListUserFiles',
                request_serializer=r2__pb2.ListUserFilesRequest.SerializeToString,
                response_deserializer=r2__pb2.ListUserFilesResponse.FromString,
                )


class R2ServiceServicer(object):
    """R2 Storage Service - Quản lý file trên Cloudflare R2
    """

    def UploadFile(self, request, context):
        """Upload file
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetFileUrl(self, request, context):
        """Get file URL (signed URL)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteFile(self, request, context):
        """Delete file
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListUserFiles(self, request, context):
        """List files by user
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_R2ServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'UploadFile': grpc.unary_unary_rpc_method_handler(
                    servicer.UploadFile,
                    request_deserializer=r2__pb2.UploadFileRequest.FromString,
                    response_serializer=r2__pb2.UploadFileResponse.SerializeToString,
            ),
            'GetFileUrl': grpc.unary_unary_rpc_method_handler(
                    servicer.GetFileUrl,
                    request_deserializer=r2__pb2.GetFileUrlRequest.FromString,
                    response_serializer=r2__pb2.GetFileUrlResponse.SerializeToString,
            ),
            'DeleteFile': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteFile,
                    request_deserializer=r2__pb2.DeleteFileRequest.FromString,
                    response_serializer=r2__pb2.DeleteFileResponse.SerializeToString,
            ),
            'ListUserFiles': grpc.unary_unary_rpc_method_handler(
                    servicer.ListUserFiles,
                    request_deserializer=r2__pb2.ListUserFilesRequest.FromString,
                    response_serializer=r2__pb2.ListUserFilesResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'r2.R2Service', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class R2Service(object):
    """R2 Storage Service - Quản lý file trên Cloudflare R2
    """

    @staticmethod
    def UploadFile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/r2.R2Service/UploadFile',
            r2__pb2.UploadFileRequest.SerializeToString,
            r2__pb2.UploadFileResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetFileUrl(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/r2.R2Service/GetFileUrl',
            r2__pb2.GetFileUrlRequest.SerializeToString,
            r2__pb2.GetFileUrlResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DeleteFile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/r2.R2Service/DeleteFile',
            r2__pb2.DeleteFileRequest.SerializeToString,
            r2__pb2.DeleteFileResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ListUserFiles(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/r2.R2Service/ListUserFiles',
            r2__pb2.ListUserFilesRequest.SerializeToString,
            r2__pb2.ListUserFilesResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
