# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: r2.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x08r2.proto\x12\x02r2\"i\n\x11UploadFileRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\x10\n\x08\x66ilename\x18\x02 \x01(\t\x12\x10\n\x08mimetype\x18\x03 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x04 \x01(\x0c\x12\x0e\n\x06\x66older\x18\x05 \x01(\t\"d\n\x12UploadFileResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07\x66ile_id\x18\x02 \x01(\t\x12\x0b\n\x03url\x18\x03 \x01(\t\x12\x0e\n\x06key_r2\x18\x04 \x01(\t\x12\x0f\n\x07message\x18\x05 \x01(\t\"?\n\x11GetFileUrlRequest\x12\x0e\n\x06key_r2\x18\x01 \x01(\t\x12\x1a\n\x12\x65xpires_in_seconds\x18\x02 \x01(\x05\"5\n\x12GetFileUrlResponse\x12\x0b\n\x03url\x18\x01 \x01(\t\x12\x12\n\nexpires_at\x18\x02 \x01(\x03\"#\n\x11\x44\x65leteFileRequest\x12\x0e\n\x06key_r2\x18\x01 \x01(\t\"6\n\x12\x44\x65leteFileResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\"C\n\x14ListUserFilesRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\x0c\n\x04page\x18\x02 \x01(\x05\x12\x0c\n\x04size\x18\x03 \x01(\x05\"n\n\x08\x46ileInfo\x12\x0f\n\x07\x66ile_id\x18\x01 \x01(\t\x12\x10\n\x08\x66ilename\x18\x02 \x01(\t\x12\x0b\n\x03url\x18\x03 \x01(\t\x12\x10\n\x08mimetype\x18\x04 \x01(\t\x12\x0c\n\x04size\x18\x05 \x01(\x03\x12\x12\n\ncreated_at\x18\x06 \x01(\x03\"_\n\x15ListUserFilesResponse\x12\x1b\n\x05\x66iles\x18\x01 \x03(\x0b\x32\x0c.r2.FileInfo\x12\r\n\x05total\x18\x02 \x01(\x05\x12\x0c\n\x04page\x18\x03 \x01(\x05\x12\x0c\n\x04size\x18\x04 \x01(\x05\x32\x88\x02\n\tR2Service\x12;\n\nUploadFile\x12\x15.r2.UploadFileRequest\x1a\x16.r2.UploadFileResponse\x12;\n\nGetFileUrl\x12\x15.r2.GetFileUrlRequest\x1a\x16.r2.GetFileUrlResponse\x12;\n\nDeleteFile\x12\x15.r2.DeleteFileRequest\x1a\x16.r2.DeleteFileResponse\x12\x44\n\rListUserFiles\x12\x18.r2.ListUserFilesRequest\x1a\x19.r2.ListUserFilesResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'r2_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_UPLOADFILEREQUEST']._serialized_start=16
  _globals['_UPLOADFILEREQUEST']._serialized_end=121
  _globals['_UPLOADFILERESPONSE']._serialized_start=123
  _globals['_UPLOADFILERESPONSE']._serialized_end=223
  _globals['_GETFILEURLREQUEST']._serialized_start=225
  _globals['_GETFILEURLREQUEST']._serialized_end=288
  _globals['_GETFILEURLRESPONSE']._serialized_start=290
  _globals['_GETFILEURLRESPONSE']._serialized_end=343
  _globals['_DELETEFILEREQUEST']._serialized_start=345
  _globals['_DELETEFILEREQUEST']._serialized_end=380
  _globals['_DELETEFILERESPONSE']._serialized_start=382
  _globals['_DELETEFILERESPONSE']._serialized_end=436
  _globals['_LISTUSERFILESREQUEST']._serialized_start=438
  _globals['_LISTUSERFILESREQUEST']._serialized_end=505
  _globals['_FILEINFO']._serialized_start=507
  _globals['_FILEINFO']._serialized_end=617
  _globals['_LISTUSERFILESRESPONSE']._serialized_start=619
  _globals['_LISTUSERFILESRESPONSE']._serialized_end=714
  _globals['_R2SERVICE']._serialized_start=717
  _globals['_R2SERVICE']._serialized_end=981
# @@protoc_insertion_point(module_scope)
